baseURL = "http://teleported.in/"
theme = "hugo-theme-minos"
languageCode = "en-us"
title = "teleported.in"
author = "Anand Saha"
description = "A blog about..."

SectionPagesMenu = "main"
[[menu.main]]
    name = "About"
    weight = -110
    identifier = "about"
    url = "/about/about"

#[[menu.main]]
#    name = "Projects"
#    weight = -110
#    identifier = "projects"
#    url = "/projects/projects"

[params]
    smartToc = true
    disqusShortname = "teleported-in"
    googleAnalytics = "UA-98287631-1"
    description = "A blog about..."
